# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Quantum Morocco 
email: quantummorocco@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ## 18-22 September, 2023. Faculty of Sciences in Rabat, Morocco.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quantummorocco.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: QuantumMorocco
instagram_username:  QuantumMorocco

# Build settings
#theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9.1.6

plugins:
  - jekyll-feed

accent_image: /assets/img/ifrane.jpg

font:         Montserrat, Helvetica, Arial, sans-serif
font_heading: Noto Sans, Helvetica, Arial, sans-serif
google_fonts: Montserrat:wght@200:700|Noto+Sans:wght@200:400,400i,700,700i

copyright:             © 2023. All rights reserved.


menu:
  - title: Group Photo
    url: /photo/
  - title: Invited Speakers
    url:  /Invited Speakers/  
  - title: Registration
    url:   /registration/
  - title: Committee
    url:   /committee/
  - title: Program
    url:   /program/
  - title: Logistics
    url:   /logistics/
  - title: Contact
    url:  /contact/





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lxock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - _posts/
  - example/_posts
